Repository 3I-shikosai32/shikosai32-front, pull requests merged in 2022-10, with the labels that each got.

#150 順位付きのユーザー情報を表示するコンポーネント`<RankedUserItem>`を作成した。
  src/components/UserItem/index.tsx
  src/features/ranking/components/RankedUserItem/RankedUserItem.story.tsx
  src/features/ranking/components/RankedUserItem/index.tsx
  src/features/ranking/components/RankedUserItem/resolveDescription.spec.ts
  src/features/ranking/components/RankedUserItem/resolveDescription.ts
Labels: ✨新機能

#151 ゲーム管理ページ用の参加ユーザーをキックするためUIを提供するコンポーネント<KickableUserInteractiveItem>を作成した。
  src/features/games/components/KickableUserInteractiveItem/KickableUserInteractiveItem.story.tsx
  src/features/games/components/KickableUserInteractiveItem/index.tsx
Labels: ✨新機能

#154 Storybookで読み込まれる`.scss`ファイルに、Figma準拠のデフォルトのフォント指定を追加した。
  src/styles/storybook.scss
Labels: 🐛バグ, 📚ライブラリ

#130 ヘッダーとフッターとメタ情報を提供する`<Layout>`を作成した。
  src/layouts/Layout.story.tsx
  src/layouts/components/Header/Header.story.tsx
  src/layouts/components/Header/index.tsx
  src/layouts/index.tsx
Labels: ✨新機能, 💡要汎用化

#156 `graphql-codegen`が生成するGraphQLのスカラー`DateTime`に対応するTypescriptの型が`any`から`Date`になるように変更した。
  codegen.yml
  package.json
  src/libs/graphql/generated/graphql.ts
  src/libs/graphql/schema.json
  src/libs/urql/index.ts
  src/libs/urql/scalarsExchange.ts
  yarn.lock
Labels: ♻リファクタリング, 📚ライブラリ

#163 Figmaの変更案の通りに`<Header>`のUIを修正した。
  src/layouts/components/Header/index.tsx
  src/layouts/components/PageNavigationMenu/index.tsx
Labels: 🐛バグ

#157 ユーザーを含む交換情報を表すコンポーネント`<TransactionItem>`と、景品交換履歴ページ用の`<GiftTransactionItem>`を作成した。
  src/components/TransactionItem/TransactionItem.story.tsx
  src/components/TransactionItem/hooks/useTransactionItem.ts
  src/components/TransactionItem/index.tsx
  src/features/history/components/GiftTransactionItem/GiftTransactionItem.story.tsx
  src/features/history/components/GiftTransactionItem/index.tsx
  src/libs/graphql/documents/fragment/GiftHistoryData.gql
  src/libs/graphql/generated/graphql.ts
Labels: ✨新機能, 💡要汎用化

#162 テキストフィールド型の入力欄を提供する`<Input>`と、それに付随する情報を表すコンポーネント群`<InputItem>` `<InputLabel>` `<InputMessage>`を作成した。
  src/components/Input/Input.story.tsx
  src/components/Input/hooks/useInputValidityState.ts
  src/components/Input/index.tsx
  tailwind.config.js
Labels: ✨新機能, 💡要汎用化

#167 `<Input>`に入力値の状態に依ってバッジを付加する機能を、コンポーネント`<InputOverlay>`として分離した。
  src/components/Input/Input.story.tsx
  src/components/Input/index.tsx
Labels: ♻リファクタリング

#168 ユーザーの情報とともに、ポイントを入力できる増減ボタン付の入力欄を表示できるコンポーネント`<PointInputUserInteractiveItem>`を作成した。
  package.json
  src/features/games/components/PointInput/PointInput.story.tsx
  src/features/games/components/PointInput/index.tsx
  src/features/games/components/PointInputUserInteractiveItem/PointInputUserInteractiveItem.story.tsx
  src/features/games/components/PointInputUserInteractiveItem/index.tsx
  yarn.lock
Labels: ✨新機能

#176 `<Header>`のリンクが操作不可能な問題を修正した
  src/components/Navigation/index.tsx
  src/layouts/components/Header/index.tsx
  src/layouts/components/PageNavigationMenu/index.tsx
  src/layouts/index.tsx
Labels: 🐛バグ, 💡要汎用化

#171 バッジの取得条件を満たしたことを通知する見た目を提供するコンポーネント`<BadgeNotification>`を作成した
  src/components/BadgeNotification/BadgeNotification.story.tsx
  src/components/BadgeNotification/index.tsx
Labels: ✨新機能

#188 各コンポーネント内の`<Link>`の宛先`href`を正しいサイト内のルーティングのものに修正した。
  src/layouts/components/HamburgerMenu/index.tsx
  src/layouts/components/PageNavigationMenu/index.tsx
  src/layouts/components/UserNavigationMenu/index.tsx
Labels: 🐛バグ

#193 `_document.tsx`内で定義されていた不要な`favicon`用の`<link>`を削除した。
  src/pages/_document.tsx
Labels: 🧊機能削除

#190 Twitter用の絶対パス指定のOGP画像を追加した。
  src/layouts/components/CommonMeta/index.tsx
Labels: 🐛バグ

#135 feat: ✨ NewUserコンポーネントを実装
  public/characters/cat.svg
  public/characters/fox.svg
  public/characters/goku.svg
  public/characters/pudding.svg
  public/characters/reaper.svg
  public/characters/tree.svg
  public/logos/new-user.png
  src/features/new-user/components/character.tsx
  src/features/new-user/components/form.tsx
  src/features/new-user/components/send.tsx
  src/features/new-user/components/upper.tsx
  src/features/new-user/hooks/useCharacter.ts
  src/features/new-user/hooks/useForm.ts
  src/features/new-user/index.tsx
  src/features/new-user/new-user.story.tsx
  src/libs/graphql/documents/mutation/createUser.gql
  src/libs/graphql/generated/graphql.ts
  src/libs/graphql/handlers/mutation/createUser.ts
  src/pages/auth/new-user.tsx
Labels: ✨新機能

#199 アニメーション付きのキャラクターコンポーネント`<LiveCharacter>`を作成した。
  public/character/fox/base.png
  public/character/fox/completed.png
  public/character/fox/item1.png
  public/character/fox/item2.png
  public/character/fox/item3.png
  public/character/fox/item4.png
  src/presentation/primitive/component/live-character/live-character.presenter.tsx
  src/presentation/primitive/component/live-character/live-character.story.tsx
Labels: ✨新機能, 💡要汎用化

#200 ゲームの参加者情報を示すコンポーネント`<GameStatusIndicator>`を作成した。
  src/presentation/relevant/game/component/game-status-indicator/game-status-indicator.presenter.tsx
  src/presentation/relevant/game/component/game-status-indicator/game-status-indicator.story.tsx
Labels: ✨新機能

#203 fix: 🐞 (useCurrentUserIdUseCase) User.id | null | undefinedを返却できるように修正
  src/presentation/layout/component/user-navigation-menu/hook/use-user-navigation-menu.hook.ts
  src/use-case/user/use-current-user-id.use-case.ts
Labels: 🐛バグ

#207 Twitter用の画像の設定`twitter:image`とTwitterのクローラーを許可する`robots.txt`を追加した。
  public/.gitkeep
  public/robots.txt
  src/presentation/layout/component/common-meta/common-meta.presenter.tsx
Labels: ✨新機能, 🐛バグ

#211 fix: 🐞 (AudioResource) 作曲者の情報を希望に合わせて変更した。
  src/state/audio/audio-resource.tsx
Labels: 🐛バグ

#220 fix: 🐞 (src/state/audio/audio-auto-play.tsx) 音楽の自動再生機能を無効化した。
  src/state/audio/audio-auto-play.tsx
Labels: 🧊機能削除

#209 景品交換ページ`/gifts`を作成した。
  next.config.js
  src/infra/graphql/document/fragment/gift-sales-data.gql
  src/infra/graphql/document/fragment/user-exchange-data.gql
  src/infra/graphql/document/mutation/exchange-gift.gql
  src/infra/graphql/document/query/find-gift-exchange-info.gql
  src/infra/graphql/document/query/find-gift-sales-data.gql
  src/infra/graphql/document/query/find-user-consumable-point.gql
  src/infra/graphql/document/subscription/updated-game-attenders.gql
  src/infra/graphql/generated/graphql.ts
  src/infra/graphql/schema.json
  src/pages/gifts.tsx
  src/presentation/relevant/gift/component/gift-item/gift-item.presenter.tsx
  src/presentation/relevant/gift/component/gift-item/gift-item.story.tsx
  src/presentation/relevant/gift/gift-index.page.tsx
  src/presentation/relevant/gift/gift-index.presenter.tsx
  src/presentation/relevant/gift/gift-index.story.tsx
  src/use-case/game/use-realtime-game-attenders.use-case.ts
  src/use-case/gift/use-exchange-gift.use-case.ts
  src/use-case/gift/use-gift-sales-data.use-case.ts
  src/use-case/user/use-user-consumable-point.use-case.ts
Labels: ✨新機能

#219 ゲーム個別ページ`/games/xeno` `/games/iceraze` `... +4`を作成した。
  src/infra/graphql/document/fragment/detailed-game-attender-data.gql
  src/infra/graphql/document/mutation/exit-game.gql
  src/infra/graphql/document/mutation/join-game.gql
  src/infra/graphql/document/subscription/updated-detailed-game-attenders.gql
  src/infra/graphql/generated/graphql.ts
  src/model/game/detailed-game-attenders.model.ts
  src/model/item/item.model.ts
  src/model/user/user.model.ts
  src/pages/games/coin-dropping.tsx
  src/pages/games/iceraze.tsx
  src/pages/games/poker.tsx
  src/pages/games/president.tsx
  src/pages/games/we-didnt-playtest.tsx
  src/pages/games/xeno.tsx
  src/presentation/layout/layout.container.tsx
  src/presentation/primitive/component/live-character/live-character.presenter.tsx
  src/presentation/relevant/game/component/game-playground/game-playground.presenter.tsx
  src/presentation/relevant/game/component/game-playground/game-playground.story.tsx
  src/presentation/relevant/game/component/game-status-indicator/game-status-indicator.presenter.tsx
  src/presentation/relevant/game/component/game-status-indicator/game-status-indicator.story.tsx
  src/presentation/relevant/game/game.page.tsx
  src/use-case/game-key-conversion-dictionary.ts
  src/use-case/game/use-realtime-detailed-game-attenders.use-case.ts
  src/use-case/game/use-realtime-game-attenders.use-case.ts
  src/use-case/user/use-exit-game.use-case.ts
  src/use-case/user/use-join-game.use-case.ts
Labels: ✨新機能

#226 fix: 🚑️ (style/stylesheet/global.scss) ページ全体が横にはみ出した要素を描画しないように変更した。
  src/presentation/style/stylesheet/global.scss
Labels: 🐛バグ

#230 feat: ✨ サインイン・サインアップ画面を作成
  src/pages/auth/index.tsx
  src/presentation/layout/component/user-navigation-menu/user-navigation-menu.presenter.tsx
  src/presentation/relevant/auth/auth.page.tsx
Labels: ✨新機能

#223 refactor: ♻ new-userの要件漏れ・設計からの逸脱を修正
  .storybook/preview.js
  package.json
  src/infra/graphql/document/query/find-all-users-name.gql
  src/infra/graphql/generated/graphql.ts
  src/infra/graphql/handler/mutation/create-user.ts
  src/infra/graphql/schema.json
  src/pages/auth/new-user.tsx
  src/presentation/primitive/component/live-character/live-character.presenter.tsx
  src/presentation/relevant/new-user/component/character-selector/character-selector.container.tsx
  src/presentation/relevant/new-user/component/character-selector/character-selector.presenter.tsx
  src/presentation/relevant/new-user/component/character/character.presenter.tsx
  src/presentation/relevant/new-user/component/email-input/email-input.container.tsx
  src/presentation/relevant/new-user/component/email-input/email-input.presenter.tsx
  src/presentation/relevant/new-user/component/form/form.presenter.tsx
  src/presentation/relevant/new-user/component/name-input/name-input.container.tsx
  src/presentation/relevant/new-user/component/name-input/name-input.presenter.tsx
  src/presentation/relevant/new-user/component/send/send.container.tsx
  src/presentation/relevant/new-user/component/send/send.presenter.tsx
  src/presentation/relevant/new-user/component/upper/upper.presenter.tsx
  src/presentation/relevant/new-user/hook/use-character.hook.ts
  src/presentation/relevant/new-user/hook/use-form.hook.ts
  src/presentation/relevant/new-user/hook/use-form.hook.tsx
  src/presentation/relevant/new-user/new-user.page.tsx
  src/presentation/relevant/new-user/new-user.story.tsx
  src/use-case/user/use-create-user.use-case.ts
  src/use-case/user/use-current-user-bio.use-case.ts
  src/use-case/user/use-find-all-users-name.use-case.ts
  yarn.lock
Labels: ✨新機能, ♻リファクタリング

#234 サインアウトページ`/auth/sign-out`を作成した。他、修正
  src/pages/auth/sign-out.tsx
  src/presentation/layout/component/user-navigation-menu/hook/use-user-navigation-menu.hook.ts
  src/presentation/relevant/auth/auth.page.tsx
  src/presentation/relevant/auth/sign-out.page.tsx
  src/presentation/relevant/auth/sign-out.presenter.tsx
  src/presentation/relevant/auth/sign-out.story.tsx
Labels: ✨新機能

#238 `<Layout>`にFirebaseで認証済みでなおかつ登録が済んでいないときにのみ表示されるモーダルを追加した。他修正
  src/presentation/layout/component/signup-progress-notification-modal/hook/use-signup-progress-notification-modal.hook.ts
  src/presentation/layout/component/signup-progress-notification-modal/signup-progress-notification-modal.container.tsx
  src/presentation/layout/component/signup-progress-notification-modal/signup-progress-notification-modal.presenter.tsx
  src/presentation/layout/component/signup-progress-notification-modal/signup-progress-notification-modal.story.tsx
  src/presentation/layout/layout.container.tsx
  src/presentation/layout/layout.story.tsx
  src/presentation/primitive/component/modal/modal.presenter.tsx
  src/presentation/primitive/component/modal/modal.story.tsx
  src/presentation/relevant/auth/auth.page.tsx
  src/use-case/user/use-current-user-authentication-status.use-case.ts
Labels: ✨新機能

#228 `useRealtimeGameAttendersUseCase` `useRealtimeDetailedGameAttendersUseCase`で初期値クエリを送るように修正した。
  src/infra/graphql/document/query/find-detailed-game-attenders.gql
  src/infra/graphql/document/query/find-game-attenders.gql
  src/infra/graphql/generated/graphql.ts
  src/infra/graphql/schema.json
  src/presentation/relevant/game/game.page.tsx
  src/use-case/game/use-realtime-detailed-game-attenders.use-case.ts
  src/use-case/game/use-realtime-game-attenders.use-case.ts
Labels: 🐛バグ, 🚑重大な問題

#244 サーバー側でのGraphQLスキーマの変更に合わせてコードを修正した。
  src/infra/graphql/document/mutation/join-game.gql
  src/infra/graphql/document/query/check-user-existance.gql
  src/infra/graphql/document/query/find-ranking-position.gql
  src/infra/graphql/document/query/find-user-consumable-point.gql
  src/infra/graphql/document/query/find-user-meta-data.gql
  src/infra/graphql/document/query/get-ranking.gql
  src/infra/graphql/document/subscription/updated-ranking.gql
  src/infra/graphql/generated/graphql.ts
  src/infra/graphql/schema.json
  src/presentation/relevant/new-user/new-user.page.tsx
  src/use-case/ranking/use-realtime-ranking-category-data.use-case.ts
Labels: ♻リファクタリング, 🐛バグ

#246 fix: 🐛 (useCurrentUserAuthenticationStatusUseCase) 読み込み中はundefinedを返す…
  src/presentation/layout/component/signup-progress-notification-modal/hook/use-signup-progress-notification-modal.hook.ts
  src/presentation/relevant/auth/auth.page.tsx
  src/presentation/relevant/new-user/new-user.page.tsx
  src/use-case/user/use-check-user-existance.use-case.ts
  src/use-case/user/use-current-user-authentication-status.use-case.ts
Labels: 🐛バグ

#249 fix: 🐛 (GraphQL Query CheckUserExistance) 受け取る変数の名前を`id`から`authId`に変更した。
  src/infra/graphql/document/query/check-user-existance.gql
  src/infra/graphql/generated/graphql.ts
  src/use-case/user/use-check-user-existance.use-case.ts
Labels: ♻リファクタリング

#253 feat: ✨ (relevant/new-user) SendのonClick時にボタンでローディングを表現するように修正
  src/presentation/relevant/new-user/component/send/send.container.tsx
  src/presentation/relevant/new-user/component/send/send.presenter.tsx
  src/presentation/relevant/new-user/new-user.page.tsx
Labels: ✨新機能, 🚑重大な問題

#248 feat: ✨ スクロールバーのスタイルを変更
  src/presentation/style/stylesheet/global.scss
Labels: ✨新機能

#255 スタイル付きのスクロールバーを作成した
  src/presentation/style/stylesheet/global.scss
Labels: ✨新機能

#254 ゲーム用管理者ページ`/games/admin/xeno`, `/games/admin/iceraze`, `... +4`を作成した。
  src/infra/graphql/document/mutation/increment-point.gql
  src/infra/graphql/generated/graphql.ts
  src/pages/games/admin/coin-dropping.tsx
  src/pages/games/admin/iceraze.tsx
  src/pages/games/admin/poker.tsx
  src/pages/games/admin/president.tsx
  src/pages/games/admin/we-didnt-playtest.tsx
  src/pages/games/admin/xeno.tsx
  src/presentation/relevant/game/component/point-input-form/point-input-form.presenter.tsx
  src/presentation/relevant/game/component/point-input-form/point-input-form.story.tsx
  src/presentation/relevant/game/component/point-input/point-input.presenter.tsx
  src/presentation/relevant/game/component/point-input/point-input.story.tsx
  src/presentation/relevant/game/component/user-kick-form/user-kick-form.presenter.tsx
  src/presentation/relevant/game/component/user-kick-form/user-kick-form.story.tsx
  src/presentation/relevant/game/game-admin.page.tsx
  src/presentation/relevant/game/game-admin.presenter.tsx
  src/presentation/relevant/game/game-admin.story.tsx
  src/presentation/relevant/game/game.page.tsx
  src/use-case/user/use-increment-point.use-case.ts
Labels: ✨新機能

#269 `<LiveCharacter>`をより小さくした。また、ゲーム個別ページで使われる`<GamePlayground>`内のキャラクターの大きさを、モバイルでのみ小さくした。
  src/presentation/primitive/component/live-character/live-character.presenter.tsx
  src/presentation/relevant/game/component/game-playground/game-playground.presenter.tsx
Labels: 🐛バグ

#271 読み込み中の画面表示用のコンポーネント`<LoadingScreen>`を作成した。
  src/presentation/primitive/component/loading-screen/loading-screen.presenter.tsx
  src/presentation/primitive/component/loading-screen/loading-screen.story.tsx
  src/presentation/relevant/game/game-admin.presenter.tsx
Labels: ✨新機能

#267 refactor: ♻ 景品交換履歴ページ及びバッジ受渡履歴ページをリファクタリング
  src/infra/graphql/document/mutation/change-delivery-state-character-status.gql
  src/infra/graphql/document/mutation/change-delivery-state-gift-history.gql
  src/infra/graphql/document/query/find-gift-histories.gql
  src/infra/graphql/document/query/find-item-completed-character-statuses.gql
  src/infra/graphql/generated/graphql.ts
  src/model/transaction/transaction.model.ts
  src/pages/admin/badge-exchange-history.tsx
  src/pages/admin/badge-transaction.tsx
  src/pages/admin/gift-exchange-history.tsx
  src/pages/admin/gift-transaction.tsx
  src/presentation/layout/component/user-navigation-menu/user-navigation-menu.presenter.tsx
  src/presentation/primitive/component/transaction-item/transaction-item.story.tsx
  src/presentation/primitive/hook/role-guard/role-guard.hook.ts
  src/presentation/relevant/badge-transaction/badge-transaction.page.tsx
  src/presentation/relevant/badge-transaction/component/badge-transaction-item/badge-transaction-item.presenter.tsx
  src/presentation/relevant/badge-transaction/component/badge-transaction-item/badge-transaction-item.story.tsx
  src/presentation/relevant/exchange-history/gift-history.page.tsx
  src/presentation/relevant/game/game-admin.page.tsx
  src/presentation/relevant/gift-transaction/component/gift-transaction-item/gift-transaction-item.presenter.tsx
  src/presentation/relevant/gift-transaction/component/gift-transaction-item/gift-transaction-item.story.tsx
  src/presentation/relevant/gift-transaction/gift-transaction.page.tsx
  src/use-case/badge-transaction/use-change-delivery-state-character-status.use-case.ts
  src/use-case/badge-transaction/use-find-item-completed-character-statuses.use-case.ts
  src/use-case/gift-transaction/use-change-delivery-state-gift-history.use-case.ts
  src/use-case/gift-transaction/use-find-gift-histories.use-case.ts
Labels: ✨新機能, ♻リファクタリング
